import time
import random
from termcolor import colored

# Christmas Colours
merry = colored('MERRY', 'green')
christmas = colored('CHRISTMAS', 'red')
# Colours
ps = colored('The Beginning', 'blue')
p2 = colored('The Adventure', 'cyan')
ASH = colored('ASH', 'red')
fight = colored('FIGHT', 'red')
flight = colored('FLIGHT', 'blue')
whole = colored('WHOLE', 'magenta')
scuba = colored('SCUBA-SUIT', 'cyan')
gameover = colored('GAME OVER', 'red')
deeper = colored('DEEPER', 'red')
shark = colored('SHARK', 'blue')
tunnel = colored('TUNNEL', 'yellow')
ocean = colored('OCEAN', 'blue')
p3 = colored('The End', 'cyan')
str = colored('[Stranger]', 'red')
stp = colored('[Steph]', 'blue')

# Global Variables
shark_death = ['true', 'false', 'true', 'false']
randpath = ['1', '2', '3']
randage = range(18, 96)

#random = random.choice(shark_death)
#rand_choice = random.choice(randpath)
age = random.choice(randage)

# Functions
def s(t):
  time.sleep(t)


def gap(num):
  for _i in range(num):
    print()


def death(reason):
  gap(1)
  print(gameover)
  print(reason)
  gap(1)
  print(f'You were: {age} years old...')


# Game
gamestart = input('START ( Y / N ): ').lower()
gap(1)
if 'y' in gamestart:
  print()
  print('DRIP')
  print()
  s(1)
  print('DRIP')
  print()
  s(1)
  print('DRIP')
  print()
  s(5)
  print('*** GASP ***')
  s(1)
  print()
  print()
  print(f''' -------------- PART 1 --------------
            {ps}''')
  print()
  s(1)
  gap(2)
  print('where..... he.. am....I')
  gap(1)
  print('** rINg **')
  s(2)
  print('Hu-huh? Wha-t-t is th-a-at s-s-sound?')
  print(
      'the player looks to their left, trying to figure out what that sound is*'
  )
  print(
      '''*they could not find the source, but in the process they found some papers reading: 
Akim Employee Files. along with your name:''')
  name = input('> ')
  gap(1)
  print(
      f'*the same sound from earlier comes back but this time theee is a voice in a female tone that says: Hello, {name} you have 3 new m-messages from, TEcHnicAl DifF-F-IcuLTYs, ErRor, ErrOR, SyStemM MaLFunCTIOn, ReeBOOtinG...'
  )
  s(5)
  gap(1)
  print(
      'System restored, I cannot connect to any Akim Database towers at the moment, please let me find the nearest tower to you...'
  )
  s(3)
  print('I have not found any towers... *RADIO STATIC* ')
  print('Please update s-system firmware.')
  print('Updating system...')
  gap(1)
  print('⌧: 10%')
  s(2)
  print('⌧⌧⌧: 35%')
  s(2)
  print('⌧⌧⌧⌧⌧: 50%')
  s(2)
  print('⌧⌧⌧⌧⌧⌧: 60%')
  s(2)
  print('⌧⌧⌧⌧⌧⌧⌧: 70%')
  s(3)
  print('Update failed.')
  gap(2)
  s(1)
  print('.')
  s(1)
  print('..')
  s(1)
  print('...')
  s(1)
  gap(1)
  print('Please find the find the nearest service technician.')
  s(2)
  print(
      f'upon further inspection {name} figured out their current situation...')
  s(3)
  gap(2)
  print(f'It is {fight} or {flight} in this new world.')
  gap(3)
  print('As you slowly look around yourself you find two paths,')
  print('Which path do you take?')
  print(f'Deeper into the Ocean {ocean}')  #make the ocean thingy blue
  print(f'Or back to the tunnel... {tunnel}')  #yellow
  path = input('> ').lower()
  gap(4)
  print(f''' -------------- PART 2 --------------
  
            {p2}''')
  gap(1)
  gap(1)
  ####################################### THE DEEP #######################################
  if path == 'deep':
    gap(1)
    print(
        f'You slowly walk into the dark abyss as it starts to swallow you {whole}...'
    )
    death('You got swallowed by the dark abyss...')
  ####################################### THE OCEAN #######################################
  if path == 'ocean':
    print('The icy cold water embraces you as you dive')
    s(1)
    print(f'A sudden relif washes over you and the {scuba} activates')
    print('***** DING *****')
    print('(explore ocean) (o) / (go back to tunnel) (t)')
    ocean = input('> ').lower()
    if ocean == 'o':
      print('You continue into the ocean as you begin')
      s(1)
      print('To swim you feel the cold embrace forced onto you lift')
      s(1)
      print('while swiming something catches your eye...')
      gap(1)
      print('Do you go down to check it out? (y/n)')
      decide = input('> ')
      if decide == 'y':
        gap(2)
        print(f'You swim deeper and {deeper} ')
        s(1)
        print(f'As you look up you see a {shark}...')
        gap(1)
        s(1)
        print(
            'In a swarm of panic you hurry and eventually get to the object...'
        )
        s(2)
        print('It\'s a scuba suit the exact same as yours...')
        s(2)
        print('The name reads "SAMUEL PETERSON"')
        s(2)
        print('You start to feel worried, but just then,')
        s(2)
        print(
            'you find another scuba suit yet this time the name is unreadable.'
        )
        s(2)
        print(
            'To your horror you hundreds more scuba suits littered all around you...'
        )
        s(2)
        print('You begin to panic and try to swim back to the shore...')
        s(2)
        print(
            'But as you try to find the shore, you realise its only sea for miles to come...'
        )
        s(2)
        print('When you finally realise whats happened you start to panic again...')
        gap(1)
        s(1)
        print('do you try to swim around some more (s)')
        s(1)
        print('or do you try to reload your GPS (m)')
        choice = input('> ')
        if choice == 's':
          print('You try to swim around some more...')
          s(1)
          print('and eventually find a cave')
          s(1)
          gap(3)
          print('You walk into the cave and find a bunch of scuba gear')
          s(1)
          print('and a few things on the wall')
          s(1)
          print('as you turn you see the akim logo spraypainted on the wall')
          s(1)
          print('you see a drink on the table')
          s(1)
          print('It still has ice cubes in it...')
          gap(3)
          print('Do you look for the owner of the den ( D )')
          print('Or swim out and away ( S )')
          dec = input('> ').lower()
          if dec == 'd':
            print()
            print()
            print()
            print('You walk down the hall to main room')
            s(1)
            print('to your horror you find a motionless body...')
            s(5)
            print('You try to scream but nothing comes out')
            s(1)
            print('The body is covered with what looks like ingection marks')
            s(1)
            print('the body is pale')
            s(1)
            print('then all of a sudden the body started to tremor as a voice murmured...')
            s(1)
            print()
            print('s-sstay  a-a-way...')
            s(1)
            print('As you wonder why,')
            print('Another gasp comes out \'nnNNnNOOOooo\'')
            s(1)
            print('You back up because you were startled')
            s(1)
            gap(1)
            print('he sighs in relif')
            s(1)
            s(1)
            print('It reads...')
            s(2)
            gap(3)
            print('The Akim project')
            print('and how the Nosyam project is related')
            print()
            print()
            print()
            print('You open it fearing the worst...')
            s(1)
            print('and finding it too...')
            gap(3)
            print('Open the book to read (R)')
            print('Or put down the book (B)')
            question = input('> ').lower()
            if question == 'r':
              print('The paper feels rough under your skin')#read
              s(1)
              print('Begin reading?')
              print('Yes (Y)')
              print('or No (N)')
              read = input('> ').lower()
              if read == 'y':
                print('You begin to read the paper')
                print("'Akim has been known for disposing")
                print('of people who are not able to do there')
                print("biding to their level with mind control'")
                input('Enter to continue: ')
                print('you look back at the person behind you')
                print('and by that point they had already passed')
                print('you look back at the book wondering who he')
                print('was and why but you put your worries to the')
                print('side and continue to read')
                input('Enter to continue: ')
                print('You begin to read the paper again')
                print('and you see the truth unvailing before you')
                print('you start to wonder if you want to continue...')
                input('Enter to continue: ')
                print('the worst part about akim is nosyam')
                print('nosyam is a company the works for')
                print('animal modification by changing their')
                print('DNA for the worst so that they can rule')
                print('animal fight arenas and they wreak havoc on')
                print('everybody because anybody can purchase')
                print('an animal with any additions...')
                print('akim and nosyam are partners in the worst')
                print('way possible...')
                input('Enter to continue: ')
                print('you put down the book')
                print('do you want to:')
                print('(L): Leave')
                print('or')
                print('(E): Explore')
                dec = input('> ').lower()
                if dec == 'l':
                  print('*BEEP* *BEEP* An alarm sounds and you start to hear something pour into the room...')
                  s(1)
                  print('*PSSSSSSSSSSSSSHHHHHHH* The room turns dark...')
                  s(1)
                  print('You find out you have been surrounded in posionous gas...')
                  s(1)
                  print('You try to escape but the door locks you in..')
                  s(1)
                  print('You lay there, taking your last breath...')
                  s(1)
                  death('You died due to gas posioning')
                elif dec == 'e':
                  print('You wonder the den trying to find anything at all to help you')
                  s(2)
                  print('but as you slowly looked back the owner of the takes the gun and')#explore the den, the person is holding a gun take da gun and explore security system donut forgor mika - i forgor mayson
                  s(0.5)
                  print('*BANG*')
                  s(3)
                  death('You died due to the owner of the den shooting you')
              else:
                print('You hear a loud rustling sound coming from behind you...')
                print('You turn around, fearing the worst...')
                print('You see the body wake and pull a gun from their old jacket...')
                print('*BANG*')
                death('You died to a gunshot wound to the head.')
            elif question == 'b':
              # holding gun, gun on their jacket, you shoot the guy as he is creeping towards you, as swimming away you see a shark and have to try to hit it using a target game (shoot1,2,3) if you miss, the shark kills u due to you missing.
              print('You put the book down')
              s(1)
              print('As soon as you do, you hear a loud rustling sound coming from behind you...')
              s(1)
              print('You turn around, fearing the literal worst...')
              s(1)
              print('Just then, the body stands up and starts slowly creeping towards you...')
              s(1)
              print('You pick up the gun and shoot...')
              s(1)
              print('You miss and he only gets closer, you begin to run...')
              s(1)
              print('As you exit, you see a shark and go to shoot it...')
              s(1)
              shark_shoot = input('Do you shoot at the sharks head (1), tail (2) or its fin (3)? ')
              if shark_shoot == '1':
                print('You shoot at the sharks head...')
                s(1)
                print('You miss and the shark eats you...')
                death('You died to a shark')
              elif shark_shoot == '2':
                print('You shoot at the sharks tail...')
                s(1)
                print('You miss and the shark turns to follow the bullet...')
                s(1)
                print('You hide behind a rock but then the shark comes back...')
                s(1)
                print('You accidently cut yourself on the rock and blood comes gushing out of your arm...')
                s(1)
                print('The shark sees the blood and gets nearer ready to chomp...')
                s(1)
                death('You died to a shark deep down in the ocean')
              elif shark_shoot == '3':
                print('You shoot at the sharks fin...')
                s(1)
                print('The bullet hits the shark right in the fin and the shark dies...')
                s(1)
                print('You continue exploring and decide to follow the red dot')
                s(1)
                print('You swim for a while and eventually find a boat...')
                s(1)
                print('as you climb aboard the massive boat')
                s(1)
                print('You hear a loud rustling sound coming from behind you...')
                s(1)
                print('You turn around, fearing the worst...')
                s(1)
                print('and finding it.')
                s(5)
                gap(4)
                print('you turn slowly only to find an akim employee')
                s(1)
                print('the employee muttered something under their breath')
            elif dec == 's':
              print('You try to swim out but the shark from before finds you...')
              s(1)
              print('Trying to escape, your suit catches on a piece of metal and rips your helmet off...')
              s(1)
              print('You try to get it back on but ultimately fail...')
              death('You drowned')
            else:
              print('You decide to swim out and away...')
        if choice == 'm':
          print('ERROR. ERROR. ERROR. Unable to *STATIC* l-load G-GPS.')
          s(2)
          print('Re-t-try-ing...')
          s(1)
          gap(1)
          print('⌧: 10%')
          s(2)
          print('⌧⌧⌧: 35%')
          s(2)
          print('⌧⌧⌧⌧⌧: 50%')
          s(2)
          print('⌧⌧⌧⌧⌧⌧: 60%')
          s(2)
          print('⌧⌧⌧⌧⌧⌧⌧: 70%')
          s(2)
          print('⌧⌧⌧⌧⌧⌧⌧⌧⌧: 90%')
          s(2)
          print('⌧⌧⌧⌧⌧⌧⌧⌧⌧⌧: 100%')
          gap(1)
          print('GPS Rel-l-oaded.')
          s(1)
          print(
              'A virtual map begins to show infront of you of your surroundings,'
          )
          s(1)
          print(' but it is nothing but pure ocean...')
          s(2)
          print('As you look closer you see a tiny red dot')
          s(1)
          print('once you tap the dot you')
          s(1)
          print('see that it is 500km away...')
          gap(2)
          s(1)
          print('You become shocked and realise that there is no escape from where you are...')
          s(1)
          print('You decide to keep swimming and eventually end up in a cave...')
          s(1)
          print(
              'Upon entering you hear a beeping noise and decide to investigate...')
          s(1)
          print('*BEEP*... *BEEP*... *BEEP*... The sound gets louder as you become near...')
          s(2)
          print('As you get closer you begin to see multipe cameras')
          s(2)
          print('Almost as if, there is a sense of security down here...')
          s(2)
          print('You decide to sneak around and find that when something is in the sight of the cameras, it tracks it...')
          gap(1)
          s(2)
          camera = input('Do you sneak around the cameras ( Y ) or do you let them see you ( N )? ').lower()
          gap(1)
          if camera == 'y':
            print('You sneak around the cameras and find that there is a group of fish surrounding you...')
            s(1)
            print('Knowing that this is extremely odd, you try to avoid them...')
            s(2)
            print('You finally get past the cameras and begin to try to open a metal door...')
            s(2)
            print('You try to open the door but it is locked...')
            s(2)
            print('You see a metal pole and grab it, then you try to barge the door open with it...')
            s(2)
            print('At last, you barge the door open just a little so you can fit through!')
            gap(1)
            s(2)
            print('You see a ladder reaching into the sky as if, you can finally escape this nightmare...')
            s(2)
            ladder = input('Do you climb the ladder ( Y ) or stay ( N )? ')
            if ladder == 'y':
              print('You decide to climb the ladder and begin to climb up, and up...')
              s(1)
              print('You climb up and up...')
              s(1)
              print('You finally reach the top when, you get taken by someone or something...')
              s(2)
              print('You try to escape its grip but ultimately fail...')
              s(2)
              print()
              print()
              print(f''' -------------- PART 3 --------------
                        {p3}''')
              print()
              s(1)
              gap(2)
              print('You hear people whispering and talking all over the place...')
              s(1)
              print('You get brought into a room and the mask over your head is taken off...')
              s(2)
              print('You are shocked to see people, you scan the environment and find that you are in some type of news room...')
              s(2)
              print(f'[{str}] Hey, who are you?')
              s(1)
              print(f'[{you}] I, I dont know, I have been trapped in the ocean for so, so long..')
              s(2)
              print(f'[{str}] Wait.... STEPH GET IN HERE...')
              s(2)
              print(f'[{stp}] Yeah?')
              s(1)
              print(f'[{str}] This is the {age} year old that went missing 10 years ago...')
              s(1)
              print(f'[{name}] What happened...')
              s(1)
              print(f'[{str}] Ten years ago, a famous employee that went by the name of {name} was just all around awesome...')
              s(1)
              print(f'[{str}] He was extermely sick for no known reason we thought nosyam was behind it but we wernt sure')
              s(1)
              print('people who went missing would have this experience...')
              s(1)
              print('but then it happened...')
              s(1)
              print('we were not allowed  to talk about it and now you wont be able to...')
              s(1)
              print('they point a gun at your head and...')
              s(1)
              print('you have a heart attack.')
              death('you died to a heart attack *face palm*')
              #the security thickens and you  grab a metal pole, you are the first person to ever survive an akim coverup and you escape and become famous with the media!
          s(1)
          print('')
      if decide == 'n':
        print('You decide to not check it out and then a shark')
        s(1)
        print('appears behind you and gets ready to bite down...')
        s(1)
        death('You died to a shark deep in the ocean...')
    if ocean == 't':
      print('You decide to go back to the tunnel...')
      s(1)
      print('As you walk back to the tunnel you hear a click')
      s(1)
      print('and then a crash.')
      s(1)
      print('You turn around and find that the tunnel that you had just entered through has collapsed...')
      s(1)
      print('You try to find a way out')
      s(1)
      print("but could'nt...")
      s(1)
      print('You realise you are trapped in the tunnel')
      s(1)
      print('and have no escape...')
      death(
          'You died due to not having any oxygen with you in the deep depths of the ocean...'
      )

  # WE NEED MORE CODE HERE URGENTLY, PLACEHOLDER FOR NOW - MAYSON - It's been coded - MIKAEL
  if path == 'tunnel':
    print('You decided to go back into the tunnel...')
    s(1)
    print('As you walk back into the tunnel you hear a click, and a creak...')
    s(1)
    print('You turn around and find that the tunnel that you had just entered through had collasped...')
    s(2)
    print('You try to find a way out but fail...')
    s(1)
    print('You realise you are trapped in the tunnel and have no escape...')
    s(1)
    print('Your breathing gets heavier...')
    s(1)
    print('You try to move but your mask gets caught on a metal rod and gets ripped off...')
    s(2)
    print('You try to place it back on in a rush but ultimately fail...')
    s(2)
    print('You lay there, taking your last breath wishing you never went out that night...')
    s(2)
    print('but then all of a sudden...')
    s(2)
    print('your scuba suit activates and suplies you with oxygen...')
    print()
    print()
    print()
    s(4)
    print('INTO THE TUNNEL')#COLOR CODE HERE RED
    print('the attack')
    s(2)
    print()
    print('You hear a nearly silent clicking noise...')
    s(1)
    print('you turn on the scuba suits flash light and decide to chase after it but pause')
    print('Where am I?')
    s(1)
    print('you start to feel light headed')
    s(1)
    print('the last thing you thought you would see was a wall')
    s(1)
    print('a wall with writing...')
    s(4)
    print('Follow the instructions (F)')
    print('or')
    print('Ignore the instructions (I)')
    s(3)
    quiz = input('> ').lower()
    s(1)
    if quiz == 'f':
      print('The instructions read...')
      s(1)
      print('once you have felt a little or alot')
      print('woozey then you should press the')
      print('green button then the red')
      input('Enter to continue: ')
      print('you press the green then red button')
      s(1)
      print('and a warning comes up')
      s(1)
      print('inject the DEVILS TRUMPET?')
      s(3)
      print('do you press yes?')
      yn = input('Y/N: ').lower()
      s(1)
      if yn == 'y':
        print('you press yes...')
        s(1)
        print('you feel yourself lift')
        s(1)
        print('and you feel a sudden burst of energy')
        s(1)
        print('you decide to follow the tunnel now')
        s(1)
        print('you go deeper...')
        s(3)
        print('and deeper...')
        s(5)
        
        print('and DEEPER.')
        s(0.5)
        print('but just then you see a light peer through')
        s(2)
        print('you emerge on a beach...')
        s(1)
        print('an alarm goes of and you decide to run...')
        s(2)
        print('but theres a split end in the road...')
        s(1)
        print('pathway 1 (1)')
        print('pathway 2 (2)')
        print('or')
        print('pathway 3 (3)')
        path = input('> ').lower()
        gap(1)
        if path == '1':
          print(f'You decide to go with pathway 1...')
          s(1)
          print('you run down the pathway and eventually find a boat')
          s(1)
          print('you ride the boat away...')
          gap(5)
          print('----20 YEARS LATER----')
          s(1)
          print('Welcome to valery news!')
          s(1)
          print(f'Today we will talk about the case of {name}.')#news report ending
          s(1)
          print('the case of the akim cover up.')
          gap(1)
          print(f'akim has been know to cover up but it was never proven.')
          s(1)
          print('akim is a serial killer that has been commiting murders')
          s(1)
          print('as a metophore and reality anyways they have been taken into custody')
          s(1)
          print(f'{name} is now dead but he will live on in our hearts.')
        elif path == '2':
        #lengthy a akim employee finds you and slowly cocks his gun, he points it at you, puts it down, thinks about his family, his life... and finally, shoots you...
          print('You run down pathway 2...')
          s(1)
          print('At the end of the pathway you find a room with metal barricades...')
          s(2)
          print('You try to open the door but someone taps on your shoulder...')
          s(2)
          print('You turn around not knowing what you will see...')
          s(2)
          print('Once you turn around you see a man in all black...')
          s(2)
          print('He pulls a gun very slowly...')
          s(2)
          print('Suddenly his hand trembles and pictures of his life flash before his eyes...')
          s(2)
          print('He pulls the gun again, mumurs to himself and...')
          s(1)
          death('You died to a bullet to the head')
        else:
          print('You head down the third path')
          s(1)
          print('You run down the path life flashing before your eyes...')
          s(2)
          print('You hear a loud bang and then a loud thud...')
          s(2)
          print('Then you hear a loud rumbling sound coming up from behind you...')
          s(2)
          print('*CRASH* It turns out it was just a mental health institution...')
          s(2)
          print('You had schizophrenia and had just been running around butt naked down the halls...')
          s(2)
          print('Those sounds were just employees chasing after you...')
          s(2)
          print('A bookshelf falls and...')
          s(1)
          death('A bookshelf flattened you and your mental health issues')
      if yn == 'n':
        print('you decide not to press yes')
        s(1)
        print('seeing as the devils trumpet is well-known')
        s(1)
        print('for its brain damage and death')
        s(1)
        print('you feel yourself slip away...')
        death('You died to the tunnel...')
    if quiz == 'i':
      print('You fade away wondering why and how you even got here')
      s(1)
      print('memorys start to flash rapidly...')
      s(1)
      print('NnNnNOOooO AnNA iM sOrRY')
      print('forgIvE mEeeEEeE')
      death('A mysterious force crumbles your head into a wall... (Wow look at this amazing art!)')
else:
  print('The sun begins to fall out of the sky...')
  s(1)
  print("You're heart beating rapidly...")
  s(1)
  print('You try to stand up but you cant...')
  s(1)
  print('The heat burns your skin...')
  s(1)
  print('You take one last breath before you pass...')
  death('You died due to the heat of the sun...')

gap(2)
s(2)
print('Thank you so much for playing!')
s(1)
print('This game was made over a long period for the P4WS game jam of 2023!')
s(2)
print('Yes, we know this game isnt completely finished and has bugs but we had fun making this game!')
s(2)
print('Feel free to play again, and again, and again, as many times as you like!')
s(2)
print('Also just a little editors note from smughotdog, if you think this was boorish or anything of the sort comment and we will try to fix it! *or add something*')
s(3)
gap(1)
print(f'{merry} {christmas}!')
print('You died due to the snow falling... and the merriest sight of all us, weirdos eating hot dogs...')
print('MURRY CRHISTLAMAS AND HARV A HAVVY NAW YAR! (mika language)')
s(1)
print('Translates to: Merry Christmas and have a happy new year!')
